### ISSUE TITLE
Center content?

### ISSUE THREAD

**Issue by beamercola** [Significa/react-snuggle#38]
Is it possible to center the items horizontally?  Everything seems to be pushed over to the left

Thanks!

**Comment by danilowoz** [comment]
Hey @beamercola, thanks for posting your question here.

Could you give us an example? A Codesandbox maybe?
I’m afraid I didn’t get your issue because the grid doesn’t have any direction actually. Once the width of the columns is the same, it is evenly distributed.

I don’t if it helps you, but what about to center the container?
```css
.grid {
   margin-left: auto;
   margin-right: auto;
}
```
